name: Coverage

on:
   push:
    branches: [ main ]
   pull_request:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: actions/checkout@v2
    - name: Ready cache
      run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/
    - name: Cache cargo
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
    - name: Install cargo-tarpaulin
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-tarpaulin
        version: latest
        use-tool-cache: true
    - name: Coverage with tarpaulin
      run: cargo tarpaulin --all --all-features --out Lcov -- --test-threads 1
    - name: Coveralls upload
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "lcov.info"
