name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: actions/checkout@v2
    - name: Ready cache
      run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/
    - name: Cache cargo
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        out-type: Lcov
        version: '0.13.0'
        args: '-- --test-threads 1'
    - name: Coveralls upload
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "lcov.info"
